name: taxly
region: nyc

services:
  - name: web
    source_dir: /
    github:
      repo: your-username/taxly
      branch: main
    build_command: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    run_command: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=8080
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: APP_NAME
        value: "Taxly"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "${APP_URL}"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        value: "${db.PORT}"
      - key: DB_DATABASE
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        value: "${db.PASSWORD}"
      - key: REDIS_HOST
        value: "${redis.HOSTNAME}"
      - key: REDIS_PORT
        value: "${redis.PORT}"
      - key: QUEUE_CONNECTION
        value: "redis"
      - key: CACHE_STORE
        value: "redis"
      - key: SESSION_DRIVER
        value: "redis"

databases:
  - name: db
    engine: MYSQL
    version: "8"
    size: db-s-dev-database
    num_nodes: 1
    dbname: taxly_db
    production: false

  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-dev-database
    num_nodes: 1
    production: false

workers:
  - name: queue
    source_dir: /
    github:
      repo: your-username/taxly
      branch: main
    build_command: |
      composer install --no-dev --optimize-autoloader
    run_command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: APP_NAME
        value: "Taxly"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        value: "${db.PORT}"
      - key: DB_DATABASE
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        value: "${db.PASSWORD}"
      - key: REDIS_HOST
        value: "${redis.HOSTNAME}"
      - key: REDIS_PORT
        value: "${redis.PORT}"
      - key: QUEUE_CONNECTION
        value: "redis"

  - name: scheduler
    source_dir: /
    github:
      repo: your-username/taxly
      branch: main
    build_command: |
      composer install --no-dev --optimize-autoloader
    run_command: |
      while true; do
        php artisan schedule:run
        sleep 60
      done
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: APP_NAME
        value: "Taxly"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        value: "${db.PORT}"
      - key: DB_DATABASE
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        value: "${db.PASSWORD}"
      - key: REDIS_HOST
        value: "${redis.HOSTNAME}"
      - key: REDIS_PORT
        value: "${redis.PORT}"
      - key: QUEUE_CONNECTION
        value: "redis"
